[1]
language:
  - php
php:
  - 7.3
  - 7.4

os: linux

install:
  - composer install

script:
  - php vendor/bin/phpunit

after_success:
  - bash <(curl -s https://codecov.io/bash)


[2]
language: php

php:
  - 5.5
  - 5.6
  - 7

before_install:
  - php /home/travis/.phpenv/versions/5.4.25/bin/composer.phar self-update

before_script:
  - composer install

script: phpunit --configuration phpunit.xml --coverage-text

[3]

language: php

php:
  - 5.5
  - 5.6
  - 7

before_install:
  - php /home/travis/.phpenv/versions/5.4.25/bin/composer.phar self-update

before_script:
  - composer install

script: phpunit --configuration phpunit.xml --coverage-text

[4]

language:
  - php
php:
  - 7.3
  - 7.4

os: linux

install:
  - composer install

script:
  - "vendor/bin/phpunit"

after_success:
  - bash <(curl -s https://codecov.io/bash)
